### ISSUE TITLE
parse_response_code returns the URL itself if code not present in URL

### ISSUE THREAD

**Issue by nikhilkv17** [perelin/spotipy_oauth_demo#3]
Since the function `parse_response_code` returns the URL itself if code is not present in the URL, A `SpotifyOAuthError` is raised while running the flask application.

logs:
 ```
Couldn't read cache at: .spotipyoauthcache
Found Spotify auth code in Request URL! Trying to get valid access token...
Couldn't read cache at: .spotipyoauthcache
[2021-01-05 18:57:40,826] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\users\nikhil karthik\anaconda3\envs\opinionify\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\nikhil karthik\anaconda3\envs\opinionify\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\nikhil karthik\anaconda3\envs\opinionify\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\nikhil karthik\anaconda3\envs\opinionify\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\nikhil karthik\anaconda3\envs\opinionify\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\nikhil karthik\anaconda3\envs\opinionify\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Nikhil Karthik\Documents\projects\opinionify\app.py", line 36, in index
    token_info = sp_oauth.get_access_token(code)
  File "c:\users\nikhil karthik\anaconda3\envs\opinionify\lib\site-packages\spotipy\oauth2.py", line 504, in get_access_token
    raise SpotifyOauthError(
spotipy.oauth2.SpotifyOauthError: error: invalid_grant, error_description: Invalid authorization code
127.0.0.1 - - [05/Jan/2021 18:57:40] "←[35m←[1mGET / HTTP/1.1←[0m" 500 - 
```

This error can for now be handled by changing the if statement (line 30) to the following:
```   
       if code != url:
            print("Found Spotify auth code in Request URL! Trying to get valid access token...")
            token_info = sp_oauth.get_access_token(code)
            access_token = token_info['access_token']```

**Comment by perelin** [comment]
@nikhilkv17 Cool, thx for looking into this. Pull Request is welcome and will be merged.
